version: '3.8'

services:
  store-web-client:
    container_name: store-web-client
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: 'dumb-init node server.js'
    ports:
      - 3001:3000
    environment:
      NEXT_PUBLIC_STORE_API_URL: http://host.docker.internal:8080
      NEXT_PUBLIC_INVOICES_URL: http://host.docker.internal:3333
