"""create credit_cards table

Revision ID: 202711267b62
Revises:
Create Date: 2022-08-17 10:00:21.996587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "202711267b62"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_cards",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("number", sa.String(length=50), nullable=False),
        sa.Column("expiration_month", sa.Integer(), nullable=False),
        sa.Column("expiration_year", sa.Integer(), nullable=False),
        sa.Column("CVV", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("limit", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credit_cards_id"), "credit_cards", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_credit_cards_id"), table_name="credit_cards")
    op.drop_table("credit_cards")
    # ### end Alembic commands ###
