"""add unique and index to number column

Revision ID: 32f16e9b8e1e
Revises: 782dc7e4591f
Create Date: 2022-09-07 16:41:53.326443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f16e9b8e1e'
down_revision = '782dc7e4591f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_credit_cards_number'), 'credit_cards', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_cards_number'), table_name='credit_cards')
    # ### end Alembic commands ###
