# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: credit_card.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x63redit_card.proto\x12\x0b\x63redit_card"\'\n\x17\x43reateCreditCardRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"\xb4\x01\n\x18\x43reateCreditCardResponse\x12\x1a\n\x12\x63redit_card_number\x18\x01 \x01(\t\x12\x18\n\x10\x63redit_card_name\x18\x02 \x01(\t\x12$\n\x1c\x63redit_card_expiration_month\x18\x03 \x01(\t\x12#\n\x1b\x63redit_card_expiration_year\x18\x04 \x01(\t\x12\x17\n\x0f\x63redit_card_CVV\x18\x05 \x01(\t2|\n\x17\x43reateCreditCardService\x12\x61\n\x10\x43reateCreditCard\x12$.credit_card.CreateCreditCardRequest\x1a%.credit_card.CreateCreditCardResponse"\x00\x62\x06proto3'
)


_CREATECREDITCARDREQUEST = DESCRIPTOR.message_types_by_name["CreateCreditCardRequest"]
_CREATECREDITCARDRESPONSE = DESCRIPTOR.message_types_by_name["CreateCreditCardResponse"]
CreateCreditCardRequest = _reflection.GeneratedProtocolMessageType(
    "CreateCreditCardRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _CREATECREDITCARDREQUEST,
        "__module__": "credit_card_pb2"
        # @@protoc_insertion_point(class_scope:credit_card.CreateCreditCardRequest)
    },
)
_sym_db.RegisterMessage(CreateCreditCardRequest)

CreateCreditCardResponse = _reflection.GeneratedProtocolMessageType(
    "CreateCreditCardResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _CREATECREDITCARDRESPONSE,
        "__module__": "credit_card_pb2"
        # @@protoc_insertion_point(class_scope:credit_card.CreateCreditCardResponse)
    },
)
_sym_db.RegisterMessage(CreateCreditCardResponse)

_CREATECREDITCARDSERVICE = DESCRIPTOR.services_by_name["CreateCreditCardService"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _CREATECREDITCARDREQUEST._serialized_start = 34
    _CREATECREDITCARDREQUEST._serialized_end = 73
    _CREATECREDITCARDRESPONSE._serialized_start = 76
    _CREATECREDITCARDRESPONSE._serialized_end = 256
    _CREATECREDITCARDSERVICE._serialized_start = 258
    _CREATECREDITCARDSERVICE._serialized_end = 382
# @@protoc_insertion_point(module_scope)
